// apps/frontend/src/components/admin/nav/button.tsx
"use client";

import Link, { LinkProps } from "next/link";
import { twMerge } from "tailwind-merge";
import clsx from "clsx";

type NavButtonProps = Omit<LinkProps, "href"> & {
  children: React.ReactNode;
  href?: string | null;
  disabled?: boolean;
  icon?: string | null;
  active?: boolean;
  title?: string;
};

export default function NavButton({
  children,
  href = "#",
  disabled = false,
  icon = null,
  active = false,
  title,
  ...props
}: NavButtonProps) {
  const finalClassName = twMerge(
    clsx(
      "inline-flex items-center gap-x-2 rounded-lg border px-4 py-2 text-base font-medium transition-all duration-500 focus:outline-hidden",
      "disabled:pointer-events-none disabled:opacity-50",
      "dark:text-zinc-200",
      {
        "text-zinc-800 hover:text-zinc-500": !disabled,
        "border-zinc-200 bg-white dark:border-zinc-800 dark:bg-zinc-800":
          active && !disabled,
        "border-transparent bg-transparent dark:bg-zinc-700":
          !active && !disabled,
        "pointer-events-none opacity-50": disabled,
      },
    ),
  );

  // Desabilita prefetch para URLs de API para evitar ações destrutivas automáticas
  const isApiRoute = (href || "#").startsWith("/api/");
  const prefetch = isApiRoute ? false : undefined;

  return (
    <Link
      href={href || "#"}
      prefetch={prefetch}
      aria-disabled={disabled}
      role="button"
      title={title}
      className={finalClassName}
      {...props}
    >
      {icon && (
        <span className={clsx(icon, "size-4 shrink-0")} aria-hidden="true" />
      )}
      {children}
    </Link>
  );
}

// src/lib/client/components/ui/Button.svelte
<script lang="ts">
	let { children, type, disabled = false, icon = null, style = 'filled', className = null, href = null } = $props()

	const classButton = {
		bordered:
			'inline-flex items-center justify-center gap-x-2 rounded-lg border border-zinc-200 bg-white px-5 py-3 font-medium shadow-xs hover:bg-zinc-50 focus:bg-zinc-50 focus:outline-none disabled:pointer-events-none disabled:opacity-50 dark:border-zinc-700 dark:bg-zinc-900 dark:hover:bg-zinc-800 dark:focus:bg-zinc-800 transition-all duration-500',
		filled:
			'inline-flex items-center justify-center gap-x-2 rounded-lg border border-transparent bg-blue-600 px-5 py-3 font-medium text-white hover:bg-blue-700 focus:bg-blue-700 focus:outline-none disabled:pointer-events-none disabled:opacity-50 transition-all duration-500'
	}
</script>

{#if href}
	<a {href} role="button" aria-disabled={disabled} class="{style === 'filled' ? classButton.filled : classButton.bordered} {className ?? 'w-full'}">
		{#if icon}
			<span class="{icon} size-4 shrink-0" aria-hidden="true"></span>
		{/if}
		{@render children()}
	</a>
{:else}
	<button {type} {disabled} class="{style === 'filled' ? classButton.filled : classButton.bordered} {className ?? 'w-full'}">
		{#if icon}
			<span class="{icon} size-4 shrink-0" aria-hidden="true"></span>
		{/if}
		{@render children()}
	</button>
{/if}
