// apps/frontend/src/components/ui/toast.tsx
"use client";

import { useCallback, useEffect, useState } from "react";
import { clsx } from "clsx";

type ToastType = "success" | "error" | "info" | "warning";
type ToastPosition = "top-left" | "top-right" | "bottom-left" | "bottom-right";

interface ToastMessage {
  id: number;
  type: ToastType;
  title: string;
  description?: string;
  duration: number;
  position: ToastPosition;
}

interface ToastWithState extends ToastMessage {
  isLeaving?: boolean;
}

const positionClasses: Record<ToastPosition, string> = {
  "top-left": "top-5 left-5",
  "top-right": "top-5 right-5",
  "bottom-left": "bottom-5 left-5",
  "bottom-right": "bottom-5 right-5",
};

const toastColors: Record<ToastType, string> = {
  success: "bg-green-600",
  error: "bg-red-600",
  info: "bg-blue-600",
  warning: "bg-yellow-600",
};

const toastIcons: Record<ToastType, string> = {
  success: "icon-[lucide--check-circle]",
  error: "icon-[lucide--x-circle]",
  info: "icon-[lucide--info]",
  warning: "icon-[lucide--alert-triangle]",
};

export default function ToastContainer() {
  const [toasts, setToasts] = useState<ToastWithState[]>([]);

  const dismiss = useCallback((id: number) => {
    setToasts((prev) =>
      prev.map((t) => (t.id === id ? { ...t, isLeaving: true } : t)),
    );

    // Tempo da animação de saída antes de remover do DOM
    setTimeout(() => {
      setToasts((prev) => prev.filter((t) => t.id !== id));
    }, 400); // mesma duração da animação .toast-out
  }, []);

  useEffect(() => {
    const handler = (event: Event) => {
      const customEvent = event as CustomEvent<ToastMessage>;
      const toast = customEvent.detail;
      setToasts((prev) => [...prev, { ...toast }]);

      if (toast.duration) {
        setTimeout(() => dismiss(toast.id), toast.duration);
      }
    };

    window.addEventListener("toast", handler);
    return () => window.removeEventListener("toast", handler);
  }, [dismiss]);

  // CSS Styles inline para as animações do Toast
  const styles = `
		@keyframes progress-bar {
			from {
				width: 100%;
			}
			to {
				width: 0%;
			}
		}

		@keyframes toast-in {
			from {
				opacity: 0;
				transform: translateY(-20px);
			}
			to {
				opacity: 1;
				transform: translateY(0);
			}
		}

		@keyframes toast-out {
			from {
				opacity: 1;
				transform: translateY(0);
			}
			to {
				opacity: 0;
				transform: translateY(-20px);
			}
		}

		.animate-progress-bar {
			animation: progress-bar linear forwards;
		}

		.animate-toast-in {
			animation: toast-in 0.5s ease forwards;
		}

		.animate-toast-out {
			animation: toast-out 0.5s ease forwards;
		}
	`;

  return (
    <>
      {/* Inject styles */}
      <style dangerouslySetInnerHTML={{ __html: styles }} />

      {(Object.keys(positionClasses) as ToastPosition[]).map((position) => (
        <div
          key={position}
          className={clsx(
            "fixed z-[1000] flex flex-col gap-3 pointer-events-none",
            positionClasses[position],
          )}
        >
          {toasts
            .filter((toast) => toast.position === position)
            .map((toast) => (
              <div
                key={toast.id}
                className={clsx(
                  "relative flex items-start gap-3 pointer-events-auto w-80 rounded-lg p-4 text-white shadow-md overflow-hidden",
                  toastColors[toast.type],
                  toast.isLeaving ? "animate-toast-out" : "animate-toast-in",
                )}
                role="alert"
              >
                <span
                  className={clsx(toastIcons[toast.type], "size-5 shrink-0")}
                />

                <div className="flex-1 text-sm">
                  <strong className="block mt-px font-semibold leading-tight">
                    {toast.title}
                  </strong>
                  {toast.description && (
                    <p className="mt-1 text-sm opacity-90 leading-tight">
                      {toast.description}
                    </p>
                  )}

                  {toast.duration > 0 && (
                    <div
                      className="absolute bottom-0 left-0 h-1 bg-white/30 animate-progress-bar"
                      style={{
                        animationDuration: `${toast.duration}ms`,
                      }}
                    />
                  )}
                </div>

                <button
                  onClick={() => dismiss(toast.id)}
                  className="opacity-75 transition hover:opacity-100"
                  aria-label="Fechar"
                >
                  <span className="icon-[lucide--x] size-4"></span>
                </button>
              </div>
            ))}
        </div>
      ))}
    </>
  );
}

// src/lib/client/components/ui/Toast.svelte
<script lang="ts">
	import { fly } from 'svelte/transition'
	import { toasts, type ToastItem, type ToastType, type ToastPosition } from '$lib/client/utils/toast'
	import { onDestroy } from 'svelte'

	let toastList: ToastItem[] = []

	const unsubscribe = toasts.subscribe((value) => {
		toastList = value
	})
	onDestroy(unsubscribe)

	const positions: ToastPosition[] = ['top-left', 'top-right', 'bottom-left', 'bottom-right']

	const dismiss = (id: string) => {
		toasts.update((all) => all.filter((t) => t.id !== id))
	}

	const toastClass = (type: ToastType) => {
		const styles = {
			success: 'bg-green-50 dark:bg-green-800 border-green-200 text-green-600 dark:border-green-800 dark:text-green-100',
			error: 'bg-red-50 dark:bg-red-800 border-red-200 text-red-600 dark:border-red-800 dark:text-red-100',
			warning: 'bg-orange-50 dark:bg-orange-800 border-orange-200 text-orange-600 dark:border-orange-800 dark:text-orange-100',
			info: 'bg-blue-50 dark:bg-blue-800 border-blue-200 text-blue-600 dark:border-blue-800 dark:text-blue-100'
		}
		return styles[type] ?? styles.info
	}
</script>

{#each positions as position}
	<!-- Container por posição -->
	<div
		class="pointer-events-none fixed z-[90] flex flex-col gap-3"
		class:top-6={position.startsWith('top')}
		class:bottom-6={position.startsWith('bottom')}
		class:left-6={position.endsWith('left')}
		class:right-6={position.endsWith('right')}
	>
		{#each toastList.filter((t) => (t.position ?? 'bottom-right') === position) as toast (toast.id)}
			<div
				in:fly={{
					y: position.startsWith('bottom') ? 50 : -50,
					duration: 250
				}}
				out:fly={{
					x: position.endsWith('right') ? 50 : -50,
					duration: 250
				}}
				class="pointer-events-auto flex w-96 items-start gap-3 rounded-xl border px-4 py-3 shadow-lg transition-all duration-300 {toastClass(toast.type)}"
				role="alert"
			>
				{#if toast.icon}
					<span class="{toast.icon} size-6 shrink-0 opacity-75"></span>
				{/if}

				<div class="flex-1">
					<div class="text-base">{toast.title}</div>
					{#if toast.description}
						<div class="mt-1 text-sm opacity-75">{toast.description}</div>
					{/if}
				</div>

				<button on:click={() => dismiss(toast.id)} class="opacity-75 transition hover:opacity-100" aria-label="Fechar">
					<span class="icon-[lucide--x] size-5"></span>
				</button>
			</div>
		{/each}
	</div>
{/each}
