// src/lib/client/components/ui/Select.svelte
<script lang="ts">
	import { onMount } from 'svelte'

	onMount(() => {
		window.HSStaticMethods.autoInit()
	})

	let { placeholder = 'Selecione uma opção...', name, selected = null, options, required = false, isInvalid, invalidMessage } = $props()
</script>

<select
	{name}
	{required}
	data-hs-select={JSON.stringify({
		placeholder,
		toggleTag: `<button type="button" aria-expanded="false"></button>`,
		toggleClasses:
			'hs-select-disabled:pointer-events-none hs-select-disabled:opacity-50 relative py-3 ps-4 pe-9 flex gap-x-2 min-w-40 text-nowrap w-full cursor-pointer bg-white border border-zinc-200 rounded-lg text-start text-base focus:outline-hidden focus:ring-2 focus:ring-blue-500 dark:bg-zinc-900 dark:border-zinc-700 dark:text-zinc-400 dark:focus:outline-hidden dark:focus:ring-1 dark:focus:ring-zinc-600',
		dropdownClasses:
			'mt-2 z-50 w-full max-h-72 p-1 space-y-0.5 bg-white border border-zinc-200 rounded-lg overflow-hidden overflow-y-auto [&::-webkit-scrollbar]:w-2 [&::-webkit-scrollbar-thumb]:rounded-full [&::-webkit-scrollbar-track]:bg-zinc-100 [&::-webkit-scrollbar-thumb]:bg-zinc-300 dark:[&::-webkit-scrollbar-track]:bg-zinc-700 dark:[&::-webkit-scrollbar-thumb]:bg-zinc-500 dark:bg-zinc-900 dark:border-zinc-700',
		optionClasses:
			'py-2 px-4 w-full text-base text-zinc-600 cursor-pointer hover:bg-zinc-100 rounded-lg focus:outline-hidden focus:bg-zinc-100 hs-select-disabled:pointer-events-none hs-select-disabled:opacity-50 dark:bg-zinc-900 dark:hover:bg-zinc-800 dark:text-zinc-200 dark:focus:bg-zinc-800',
		optionTemplate: `<div class="flex justify-between items-center w-full">
			<span data-title></span>
			<span class="hidden hs-selected:block">
				<span class="icon-[lucide--check] size-3.5 shrink-0 text-blue-600 dark:text-blue-500"></span>
			</span></div>`,
		extraMarkup: `<div class="absolute top-1/2 end-3 -translate-y-1/2">
										<span class="icon-[lucide--chevrons-up-down] size-3.5 shrink-0 text-zinc-500 dark:text-zinc-500"></span>
		</div>`
	})}
	class="hidden"
>
	<option selected={selected === ''}></option>
	{#each options as { label, value, disabled } (value)}
		<option {value} {disabled} selected={selected === value}>{label}</option>
	{/each}
</select>

{#if isInvalid}
	<p class="dark:text-red-00 mt-2 text-xs text-red-500">{invalidMessage}</p>
{/if}

// apps/web/src/components/ui/select.tsx
"use client";

import {
  useState,
  useRef,
  useEffect,
  KeyboardEvent,
  HTMLAttributes,
} from "react";
import { clsx } from "clsx";
import { twMerge } from "tailwind-merge";

export interface SelectOption {
  label: string;
  value: string;
  disabled?: boolean;
}

export interface SelectProps extends Omit<
  HTMLAttributes<HTMLDivElement>,
  "onChange"
> {
  placeholder?: string;
  name: string;
  selected?: string | null;
  options: SelectOption[];
  required?: boolean;
  onChange?: (value: string) => void;
  clearable?: boolean;
  onClear?: () => void;
  isInvalid?: boolean;
  invalidMessage?: string;
}

export default function Select({
  placeholder = "Selecione...",
  id,
  name,
  selected = null,
  isInvalid = false,
  invalidMessage,
  options,
  required = false,
  onChange,
  clearable = false,
  onClear,
  ...props
}: SelectProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [search, setSearch] = useState("");
  const [highlight, setHighlight] = useState(0);
  const [openUpwards, setOpenUpwards] = useState(false);

  const containerRef = useRef<HTMLDivElement>(null);
  const dropdownRef = useRef<HTMLDivElement>(null);

  const filtered = options.filter((opt) =>
    opt.label.toLowerCase().includes(search.toLowerCase()),
  );
  const hasSelection = selected !== null && selected !== undefined;
  const selectedLabel = options.find((opt) => opt.value === selected)?.label;
  const canClear =
    clearable && selected !== null && selected !== undefined && selected !== "";

  useEffect(() => {
    function onClickOutside(e: MouseEvent) {
      if (
        !containerRef.current?.contains(e.target as Node) &&
        !dropdownRef.current?.contains(e.target as Node)
      ) {
        setIsOpen(false);
      }
    }
    document.addEventListener("mousedown", onClickOutside);
    return () => document.removeEventListener("mousedown", onClickOutside);
  }, []);

  useEffect(() => {
    if (isOpen && containerRef.current) {
      const rect = containerRef.current.getBoundingClientRect();
      const viewportHeight = window.innerHeight;
      const dropdownHeight = 240; // altura aproximada: search (40px) + lista (200px)

      const spaceBelow = viewportHeight - rect.bottom;
      const spaceAbove = rect.top;

      setOpenUpwards(
        spaceBelow < dropdownHeight && spaceAbove > dropdownHeight,
      );
    }
  }, [isOpen]);

  const toggle = () => setIsOpen((prev) => !prev);

  const selectOption = (opt: SelectOption) => {
    if (opt.disabled) return;
    if (opt.value !== selected) {
      onChange?.(opt.value);
    }
    setIsOpen(false);
    setSearch("");
    setHighlight(0);
  };

  const onKeyDown = (e: KeyboardEvent<HTMLDivElement>) => {
    if (!isOpen) return;

    if (e.key === "ArrowDown") {
      e.preventDefault();
      setHighlight((h) => Math.min(h + 1, filtered.length - 1));
    }
    if (e.key === "ArrowUp") {
      e.preventDefault();
      setHighlight((h) => Math.max(h - 1, 0));
    }
    if (e.key === "Enter") {
      e.preventDefault();
      selectOption(filtered[highlight]);
    }
    if (e.key === "Escape") {
      e.preventDefault();
      setIsOpen(false);
    }
  };

  return (
    <div
      ref={containerRef}
      onKeyDown={onKeyDown}
      className="relative w-full"
      {...props}
    >
      {/* Toggle */}
      <button
        id={id}
        type="button"
        onClick={toggle}
        aria-haspopup="listbox"
        aria-expanded={isOpen}
        className={twMerge(
          clsx(
            "relative w-full cursor-pointer rounded-lg border bg-white pl-4 py-3 text-left text-base text-zinc-700 transition focus:outline-none",
            canClear ? "pr-16" : "pr-10",
            "dark:bg-zinc-900 dark:border-zinc-700 dark:text-zinc-200",
            isInvalid
              ? "border-red-400 focus:border-red-400 focus:ring-1 focus:ring-red-600 dark:border-red-800 dark:focus:border-red-800 dark:focus:ring-red-800"
              : "focus:border-blue-500 focus:ring-1 focus:ring-blue-500 dark:focus:ring-zinc-600",
            {
              "border-blue-300": isOpen && !isInvalid,
              "border-zinc-200": !isOpen && !isInvalid,
            },
          ),
        )}
      >
        <span className="block w-full truncate">
          {hasSelection && selectedLabel ? (
            selectedLabel
          ) : (
            <span className="text-zinc-400">
              {placeholder ?? "Selecione..."}
            </span>
          )}
        </span>

        {/* Ícone */}
        <span className="pointer-events-none absolute inset-y-0 right-3 flex items-center text-zinc-400 dark:text-zinc-500">
          <span
            className={twMerge(
              "icon-[lucide--chevron-down] size-4 transition-transform duration-200 ease-in-out",
              isOpen && "rotate-180",
            )}
          />
        </span>
      </button>

      {canClear && (
        <button
          type="button"
          onClick={(e) => {
            e.preventDefault();
            e.stopPropagation();
            if (onClear) onClear();
            else onChange?.("");
            setIsOpen(false);
            setSearch("");
            setHighlight(0);
          }}
          className="absolute inset-y-0 right-9 flex items-center text-zinc-400 hover:text-zinc-600 dark:text-zinc-500 dark:hover:text-zinc-300"
          aria-label="Limpar seleção"
          title="Limpar seleção"
        >
          <span className="icon-[lucide--x] size-4" />
        </button>
      )}

      {/* Dropdown */}
      {isOpen && (
        <div
          ref={dropdownRef}
          className={twMerge(
            clsx(
              "absolute z-50 w-full max-h-80 overflow-hidden rounded-lg bg-white shadow-lg dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-700",
              openUpwards ? "bottom-full mb-1" : "top-full mt-1",
            ),
          )}
        >
          {/* Search */}
          <div className="px-3 py-2">
            <input
              type="text"
              name="search"
              value={search}
              onChange={(e) => {
                setSearch(e.target.value);
                setHighlight(0);
              }}
              className="block w-full rounded-lg border border-zinc-200 bg-zinc-50 px-3 py-2 text-base focus:outline-none focus:ring-2 focus:ring-blue-500 dark:border-zinc-600 dark:bg-zinc-800 dark:text-zinc-200"
              placeholder="Buscar..."
              autoFocus
            />
          </div>

          <ul role="listbox" className="max-h-64 overflow-y-auto pb-1">
            {filtered.length > 0 ? (
              filtered.map((opt, idx) => (
                <li
                  key={opt.value}
                  role="option"
                  aria-selected={selected === opt.value}
                  onClick={() => selectOption(opt)}
                  onMouseEnter={() => setHighlight(idx)}
                  className={twMerge(
                    clsx(
                      "flex cursor-pointer items-center justify-between px-4 py-2 text-base transition group",
                      {
                        "bg-blue-50 dark:bg-zinc-800": idx === highlight,
                        "opacity-50 cursor-not-allowed": opt.disabled,
                      },
                    ),
                  )}
                >
                  <span
                    className={twMerge(
                      clsx("transition-colors", {
                        "group-hover:text-zinc-800 dark:group-hover:text-zinc-100":
                          !opt.disabled,
                        "text-zinc-900 dark:text-zinc-100": idx === highlight,
                      }),
                    )}
                  >
                    {opt.label}
                  </span>
                  {selected === opt.value && (
                    <span className="icon-[lucide--check] size-4 text-blue-600 dark:text-blue-500" />
                  )}
                </li>
              ))
            ) : (
              <li className="px-4 py-2 text-base text-zinc-500">
                Nenhuma opção
              </li>
            )}
          </ul>
        </div>
      )}

      {/* Input hidden para formulário */}
      <input
        type="hidden"
        name={name}
        value={selected ?? ""}
        required={required}
      />

      {isInvalid && <Message>{invalidMessage}</Message>}
    </div>
  );
}

function Message({ children }: { children: React.ReactNode }) {
  return (
    <p className="mt-2 text-xs text-red-500 dark:text-red-600">{children}</p>
  );
}
