// src/lib/client/components/app/tab/Button.svelte
<script lang="ts">
	let { children, id, tab, active = false }: { children: any; id: string; tab: string; active?: boolean } = $props()
</script>

<button
	type="button"
	class="hs-tab-active:bg-white hs-tab-active:border-zinc-200 hs-tab-active:dark:border-zinc-800 hs-tab-active:dark:bg-zinc-800 {active
		? 'active'
		: ''} inline-flex items-center gap-x-2 rounded-lg border border-transparent bg-transparent px-4 py-2 text-base font-medium text-zinc-800 transition-all duration-500 hover:text-zinc-500 focus:outline-hidden disabled:pointer-events-none disabled:opacity-50 dark:bg-zinc-700 dark:text-zinc-200"
	{id}
	aria-selected="true"
	data-hs-tab="#{tab}"
	aria-controls={tab}
	role="tab"
>
	{@render children()}
</button>

// apps/frontend/src/components/admin/nav/button.tsx
"use client";

import Link, { LinkProps } from "next/link";
import { twMerge } from "tailwind-merge";
import clsx from "clsx";

type NavButtonProps = Omit<LinkProps, "href"> & {
  children: React.ReactNode;
  href?: string | null;
  disabled?: boolean;
  icon?: string | null;
  active?: boolean;
  title?: string;
};

export default function NavButton({
  children,
  href = "#",
  disabled = false,
  icon = null,
  active = false,
  title,
  ...props
}: NavButtonProps) {
  const finalClassName = twMerge(
    clsx(
      "inline-flex items-center gap-x-2 rounded-lg border px-4 py-2 text-base font-medium transition-all duration-500 focus:outline-hidden",
      "disabled:pointer-events-none disabled:opacity-50",
      "dark:text-zinc-200",
      {
        "text-zinc-800 hover:text-zinc-500": !disabled,
        "border-zinc-200 bg-white dark:border-zinc-800 dark:bg-zinc-800":
          active && !disabled,
        "border-transparent bg-transparent dark:bg-zinc-700":
          !active && !disabled,
        "pointer-events-none opacity-50": disabled,
      },
    ),
  );

  // Desabilita prefetch para URLs de API para evitar ações destrutivas automáticas
  const isApiRoute = (href || "#").startsWith("/api/");
  const prefetch = isApiRoute ? false : undefined;

  return (
    <Link
      href={href || "#"}
      prefetch={prefetch}
      aria-disabled={disabled}
      role="button"
      title={title}
      className={finalClassName}
      {...props}
    >
      {icon && (
        <span className={clsx(icon, "size-4 shrink-0")} aria-hidden="true" />
      )}
      {children}
    </Link>
  );
}
