// src/lib/dashboard/ChartColumn.svelte
<script lang="ts">
	import { onMount, onDestroy } from 'svelte'

	let chartContainer: HTMLDivElement
	let chart: any = null

	let isClient = false
	onMount(() => {
		isClient = true
	})

	let series = $state([
		{
			name: 'Incidentes',
			data: [44, 55, 41, 67, 22, 43, 21, 33, 45, 31]
		}
	])

	let chartOptions = $state({
		chart: {
			type: 'bar',
			toolbar: {
				show: false
			}
		},
		plotOptions: {
			bar: {
				borderRadius: 8,
				columnWidth: '50%'
			}
		},
		dataLabels: {
			enabled: false
		},
		stroke: {
			width: 0
		},
		grid: {
			show: false,
			row: {
				colors: ['#fff', '#f2f2f2']
			}
		},
		xaxis: {
			labels: {
				rotate: -45
			},
			categories: ['25 fev', '26 fev', '27 fev', '28 fev', '01 mar', '02 mar', '03 mar', '04 mar', '05 mar', '06 mar']
		},
		fill: {
			type: 'gradient',
			gradient: {
				shade: 'light',
				type: 'horizontal',
				shadeIntensity: 0.25,
				gradientToColors: undefined,
				inverseColors: true,
				opacityFrom: 0.85,
				opacityTo: 0.85,
				stops: [50, 0, 100]
			}
		}
	})

	onMount(async () => {
		const ApexCharts = (await import('apexcharts')).default // Import dinâmico
		chart = new ApexCharts(chartContainer, {
			chart: chartOptions.chart,
			series,
			plotOptions: chartOptions.plotOptions,
			dataLabels: chartOptions.dataLabels,
			stroke: chartOptions.stroke,
			grid: chartOptions.grid,
			xaxis: chartOptions.xaxis,
			fill: chartOptions.fill
		})

		chart.render()
	})

	onDestroy(() => {
		chart?.destroy()
	})
</script>

<div bind:this={chartContainer} class="w-full"></div>

// src/components/admin/dashboard/ChartColumn.tsx
"use client";

import dynamic from "next/dynamic";
import { useState, useEffect, useMemo } from "react";
import type { ApexOptions } from "apexcharts";

// Importação dinâmica para evitar SSR
const ReactApexChart = dynamic(() => import("react-apexcharts"), {
  ssr: false,
});

export default function ChartColumn({
  categories,
  data,
}: {
  categories: string[];
  data: number[];
}) {
  const [isClient, setIsClient] = useState(false);

  // Tons claros para cada faixa
  const LIGHT = {
    green: "#05DF72",
    orange: "#FF8904",
    red: "#e7000b",
  };

  // Arrays de cores por barra (claro)
  const leftColors = useMemo(() => {
    const left: string[] = [];

    data.forEach((v) => {
      if (v <= 2) {
        left.push(LIGHT.green);
      } else if (v <= 4) {
        left.push(LIGHT.orange);
      } else {
        left.push(LIGHT.red);
      }
    });

    return left;
  }, [data, LIGHT.green, LIGHT.orange, LIGHT.red]);

  const series = useMemo(
    () => [
      {
        name: "Incidentes",
        data,
      },
    ],
    [data],
  );

  const options: ApexOptions = useMemo(
    () => ({
      chart: {
        type: "bar",
        toolbar: { show: false },
      },
      plotOptions: {
        bar: {
          distributed: true,
          borderRadius: 8,
          columnWidth: "50%",
        },
      },
      legend: { show: false },
      colors: leftColors,
      dataLabels: { enabled: false },
      stroke: { width: 0 },
      grid: {
        show: false,
        row: {
          colors: ["#fff", "#f2f2f2"],
        },
      },
      xaxis: {
        categories,
        labels: { rotate: -45 },
      },
      fill: {
        type: "gradient",
        gradient: {
          shade: "light",
          type: "horizontal",
          shadeIntensity: 0.25,
          gradientToColors: undefined,
          opacityFrom: 0.85,
          opacityTo: 0.85,
          stops: [50, 0, 100],
        },
      },
    }),
    [categories, leftColors],
  );

  useEffect(() => {
    setIsClient(true);
  }, []);

  return (
    <div className="w-full max-w-lg">
      {isClient && (
        <ReactApexChart
          options={options}
          series={series}
          type="bar"
          height={320}
        />
      )}
    </div>
  );
}
